### Опрерації над масивами

In [4]:
message="""З двовимірними масивами можна працювати як з алгебраїчними матрицями"""
def homework(message):
   print("\n>>>>>",message, "\n")
import numpy as np
homework(message)


>>>>> З двовимірними масивами можна працювати як з алгебраїчними матрицями 



##### Згенеруємо декілька масивів різними способами та виконаємо базові математичні операції

In [17]:
l = (3, 3)

O = np.ones(l)
print('Матриця О:\n', O)
R = np.random.random(l)
print('Матриця R:\n', R)
Z = np.zeros(l)
print('Матриця Z:\n', Z)
C = np.arange(l[0])
print('Матриця C:\n', C)

print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")

Матриця О:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Матриця R:
 [[0.81052977 0.7378515  0.29716613]
 [0.36173047 0.50253952 0.98152345]
 [0.285508   0.5499272  0.27541168]]
Матриця Z:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Матриця C:
 [0 1 2]

Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.81052977 0.7378515  0.29716613]
 [0.36173047 0.50253952 0.98152345]
 [0.285508   0.5499272  0.27541168]]
Ділення:
 [[       inf 0.7378515  0.14858306]
 [       inf 0.50253952 0.49076172]
 [       inf 0.5499272  0.13770584]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[ True  True False]
 [False  True  True]
 [False  True False]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]



C:\Users\NewUser\AppData\Local\Temp\ipykernel_25964\928280572.py:15: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
C:\Users\NewUser\AppData\Local\Temp\ipykernel_25964\928280572.py:18: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


In [28]:
A=np.eye(4)
print('Одинична діагональна матриця, створена методом `np.eye`:\n', A)
print('\nПорівняння елементів матриці А на наявність 1:\n', A==1)
B=np.ones((4,4))
print('\nМатриця В, створена методом `np.ones`:\n', B)
print('\nРізниця матриць (B-A):\n', B-A)

Одинична діагональна матриця, створена методом `np.eye`:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Порівняння елементів матриці А на наявність 1:
 [[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]

Матриця В, створена методом `np.ones`:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Різниця матриць (B-A):
 [[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]


### Множення матриць

In [33]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n\n {B}")

R = A * B
print(f"\nПоелементне множення масивів:\n {R}")

R = np.dot(A, B)
print(f"\nТут, масиви перемножуються як матриці:\n {R}")

MA = np.mat(A)
MB = np.mat(B)

R = MA * MB
print(f"\nТут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 

 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]

Поелементне множення масивів:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]

Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]

Тут масиви перетворені на матриці і далі перемножуються:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


### Вирівнювання розмірностей

In [35]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком з трьох елементів {B.shape}: {B}, тому додавання (A+B) буде по рядках:\n {A + B}")
print(f"""\nВектор C є стовпцем {C.shape}:
{C}
\nтому додавання буде по стовпцях:
{A + C}""")
print(f"\nУ випадку додавання рядка до стовпця результуючою буде матриця, в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком з трьох елементів (3,): [1 2 3], тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]

Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]

тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]

У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


### Конкатенація, повторення та зміна форми (shape)

In [48]:
D = np.ones(3)
Z = np.zeros((3,1))
print('Матриця D:', D)
print('Матриця Z:\n', Z)
print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}")
\nПри конкатенації стовпців маємо:\n{np.concatenate((Z, Z))}
\nМасив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з В {B} розмірністю {B.shape}:
{np.concatenate((B, D))}
\nДля конкатенації з С
{C}
де С має розмірність = {C.shape} потрібно змінити розмірність D = {D.shape}
\nЦе можна зробити так:
{D[:, np.newaxis].shape}
або
{D.reshape((3,1)).shape}
в результаті можемо виконати конкатенацію:
{np.concatenate((C, D.reshape((3,1))))}
\nПри повторенні D {D} 2 рази для рядкі та 3 для стовпців будем мати:
{np.tile(D, (2, 3))}
\nЯк бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}
\nТакож можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
""")

Матриця D: [1. 1. 1.]
Матриця Z:
 [[0.]
 [0.]
 [0.]]

При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]")

При конкатенації стовпців маємо:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з В [1 2 3] розмірністю (3,):
[1. 2. 3. 1. 1. 1.]

Для конкатенації з С
[[1]
 [2]
 [3]]
де С має розмірність = (3, 1) потрібно змінити розмірність D = (3,)

Це можна зробити так:
(3, 1)
або
(3, 1)
в результаті можемо виконати конкатенацію:
[[1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [1.]]

При повторенні D [1. 1. 1.] 2 рази для рядкі та 3 для стовпців будем мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]

Також можна перетворити двовимірний масив A розмірністю (3, 3) на рядок: [11 12 13 21 22 23 31 32 33] з розмірністю (9,)



In [74]:
a = np.arange(9).reshape((3, 3))
print('Створений за допомогою `arange` двохвимірний масив `а` розмірністю 3х3:\n', a)
print('\nМасив `а` після конкатенації:\n', np.concatenate((a,a)))
print('\nМасив `а` після повторення:\n', np.tile(a,3))

b = np.arange(10,16).reshape((3, 2))
print('\nСтворений за допомогою `arange` масив `b` розмірністю 3х2:\n', b)
print('\nОскільки, розмірність масивів `а`(3x3) і `b`(3x2) не співпадає, то змінимо розмірність масиву `b`:\n', b.reshape(2,3) ,
'\n\nта виконаємо конкатенацію масивів `a` і `b`:\n', np.concatenate((a, b.reshape(2,3))))


Створений за допомогою `arange` двохвимірний масив `а` розмірністю 3х3:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Масив `а` після конкатенації:
 [[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]

Масив `а` після повторення:
 [[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]
 [6 7 8 6 7 8 6 7 8]]

Створений за допомогою `arange` масив `b` розмірністю 3х2:
 [[10 11]
 [12 13]
 [14 15]]

Оскільки, розмірність масивів `а`(3x3) і `b`(3x2) не співпадає, то змінимо розмірність масиву `b`:
 [[10 11 12]
 [13 14 15]] 

та виконаємо конкатенацію масивів `a` і `b`:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]]


In [73]:
print('Створила двовимірний масив `c` (розмірністю 1х12) та знайшла всі можливі комбінації reshape.\n') 
c=np.arange(12).reshape(1,12)
print(c)
c=np.arange(12).reshape(2,6)
print('\n', c)
c=np.arange(12).reshape(3,4)
print('\n', c)
c=np.arange(12).reshape(4,3)
print('\n', c)
c=np.arange(12).reshape(6,2)
print('\n', c)
c=np.arange(12).reshape(12,1)
print('\n', c)

Створила двовимірний масив `c` (розмірністю 1х12) та знайшла всі можливі комбінації reshape.

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]

 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


### Трансформації масивів

In [75]:
O = np.arange(6).reshape(3,2)
O_r = O.reshape((2,3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)

print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]



In [103]:
t=np.arange(20,32)
print('Створила вектор `t` з 12 елементів:\n', t, 
'\n\nВизначила:\n`shape` вектора `t`:', t.shape, '\n`size` вектора `t`:', t.size, '\n`ndim` вектора `t`:', t.ndim)
t1=np.arange(20,32).reshape(3,4)
print('\nПеретворила вектор `t` у матрицю `t1` розмірністю 3х4:\n', t1)
t3 = t1.transpose()
t4 = np.flip(t3)
print('\nТранспонувала матрицю `t1`:\n', t3, '\n\nОбернула матрицю `t1` (по стовпцях і рядках одночасно):\n', t4)
t5 = t4.flatten()
print('\nПеретворила отриманий багатовимірний масив назад у вектор (стрічку):\n', t5)

Створила вектор `t` з 12 елементів:
 [20 21 22 23 24 25 26 27 28 29 30 31] 

Визначила:
`shape` вектора `t`: (12,) 
`size` вектора `t`: 12 
`ndim` вектора `t`: 1

Перетворила вектор `t` у матрицю `t1` розмірністю 3х4:
 [[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

Транспонувала матрицю `t1`:
 [[20 24 28]
 [21 25 29]
 [22 26 30]
 [23 27 31]] 

Обернула матрицю `t1` (по стовпцях і рядках одночасно):
 [[31 27 23]
 [30 26 22]
 [29 25 21]
 [28 24 20]]

Перетворила отриманий багатовимірний масив назад у вектор (стрічку):
 [31 27 23 30 26 22 29 25 21 28 24 20]
