### Робота з простими лістами

In [4]:
%time
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print('Список заданих температурних значень: ',temperature)

t1 = temperature * 5
print(f"При множенні списку temperature на 5 отримуємо: {t1}")

CPU times: total: 0 ns
Wall time: 0 ns
Список заданих температурних значень:  [20.1, 20.1, 20.2, 20.4]
При множенні списку temperature на 5 отримуємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]


In [5]:
t1=list()
for x in temperature:
    t1.append(x*5+30)
print(f"При множенні на 5 та збільшенні на 30 значення кожного елементу зі списку temperature отримуємо: {t1}")

t1 = [ x*5+30 for x in temperature] 
print(f"Тепер отримаємо: {t1}")

При множенні на 5 та збільшенні на 30 значення кожного елементу зі списку temperature отримуємо: [130.5, 130.5, 131.0, 132.0]
Тепер отримаємо: [130.5, 130.5, 131.0, 132.0]


### Робота з лістами в бібліотеці `numpy`

In [16]:
t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2, type(t2))

t3 = t2 * 5 + 30
print("При множенні елементів масиву на 5 отримуємо:", t3)

t3 = t2 % 5
print("Остача від ділення на 5:", t3)

Масив з використанням методів NumPy [20.1 20.1 20.2 20.4] <class 'numpy.ndarray'>
При множенні на 5 отримуємо: [130.5 130.5 131.  132. ]
Остача від ділення на 5: [0.1 0.1 0.2 0.4]


### **Вектори, створення та робота з ними**

In [50]:
l1=[1, 2, 3, 4, 5]
l2=[6, 7, 8, 9, 10]
l3=[11, 12, 13, 14, 15]
vector_1=np.array(l1)
vector_2=np.array([l1, l2])
vector_3=np.array([l1, l2, l3])
vector_4=np.array([[l1, l2, l3], [l1, l2, l3], [l1, l2, l3], [l1, l2, l3]])

print(f"Це є list: {l1}\n\n Масив numpy `vector_1`: {vector_1} \n\n Масив numpy `vector_2`:\n {vector_2} \n\n Масив numpy `vector_3`:\n {vector_3} \n\n Масив numpy `vector_4`:\n {vector_4}")

t1=vector_1*7
t2=vector_2*7
t4=vector_4*7
print(f"\nРезультат множення елементів масиву 'vector_1' на 7: {t1}, \n Результат множення масиву 'vector_2' на 7: {t2}, \n Результат множення масиву 'vector_4' на 7: {t4}")

Це є list: [1, 2, 3, 4, 5]

 Масив numpy `vector_1`: [1 2 3 4 5] 

 Масив numpy `vector_2`:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

 Масив numpy `vector_3`:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

 Масив numpy `vector_4`:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]

Результат множення елементів масиву 'vector_1' на 7: [ 7 14 21 28 35], 
 Результат множення масиву 'vector_2' на 7: [[ 7 14 21 28 35]
 [42 49 56 63 70]], 
 Результат множення масиву 'vector_4' на 7: [[[  7  14  21  28  35]
  [ 42  49  56  63  70]
  [ 77  84  91  98 105]]

 [[  7  14  21  28  35]
  [ 42  49  56  63  70]
  [ 77  84  91  98 105]]

 [[  7  14  21  28  35]
  [ 42  49  56  63  70]
  [ 77  84  91  98 105]]

 [[  7  14  21  28  35]
  [ 42  49  56  63  70]
  [ 77  84  91  98 105]]]


### Розмірність масиву

In [49]:
print("\nОдновимірний масив (або вектор) розмірністю [5] елементів:", vector_1.shape)
print("Двовимірний масив, розмірністю [2x5] елементів:", vector_2.shape)
print("Двовимірний масив, розмірністю [3x5] елементів:", vector_3.shape)
print("Тривимірний масив, розмірністю [4х3x5] елементів:", vector_4.shape)


Одновимірний масив (або вектор) розмірністю [5] елементів: (5,)
Двовимірний масив, розмірністю [2x5] елементів: (2, 5)
Тривимірний масив, розмірністю [3x5] елементів: (3, 5)
Багатовимірний масив: (4, 3, 5)


In [53]:
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір:", vector_row.shape, "\n")
print(vector_column, "\nВектор має розмір:", vector_column.shape)

[[ 1 -5  3  2  4]] 
Вектор має розмір: (1, 5) 

[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір: (4, 1)


### Метод arange - генерує послідовність чисел з певним кроком у заданому інтервалі

In [46]:
a=range(1,10,2)
print('Вивід значень від 1 до 9 з кроком 2: ', list(a))

b=np.arange(1,11)
print('Вивід значень від 1 до 10: ', b)
print('Розмірність вектора b (одновимірний з 10 елементів): ',b.shape)
print('Вивід першого елементу масиву b[0]=', b[0])
print('Вивід останнього елементу масиву b[9]=', b[-1], '\n')

print('Вивід всіх елементів масиву методом слайсинг:', b[:])
print('Вивід всіх елементів масиву від 0 до 2 методом слайсинг:', b[0:2])
print('Вивід перших 5 елементів масиву методом слайсинг:', b[0:5])
print('Вивід елементів масиву від 4 до 6 методом слайсинг:', b[3:6])

c=np.array([b[0:3], b[3:6], b[-4:-1]])
print('Вивід тривимірного numpy масиву с методом слайсинг:\n', c)

Вивід значень від 1 до 9 з кроком 2:  [1, 3, 5, 7, 9]
Вивід значень від 1 до 10:  [ 1  2  3  4  5  6  7  8  9 10]
Розмірність вектора b (одновимірний з 10 елементів):  (10,)
Вивід першого елементу масиву b[0]= 1
Вивід останнього елементу масиву b[9]= 10 

Вивід всіх елементів масиву методом слайсинг: [ 1  2  3  4  5  6  7  8  9 10]
Вивід всіх елементів масиву від 0 до 2 методом слайсинг: [1 2]
Вивід перших 5 елементів масиву методом слайсинг: [1 2 3 4 5]
Вивід елементів масиву від 4 до 6 методом слайсинг: [4 5 6]
Вивід тривимірного numpy масиву с методом слайсинг:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {list(x[0:5])} та методом arange: {a[0:5]}")
print('\n!!!HOMEWORK!!!')
print(f"Весь діапазон масиву, згенерований простим range: {list(x[start:size_of_vec])}")
print(f"Весь діапазон масиву, згенерований методом arange з кроком 3:\n {a[start:size_of_vec:3]}")
print(f"Весь діапазон масиву, згенерований методом arange в зворотньому порядку:\n {a[::-1]}")
#homework("Виведіть весь діапазон чисел.")

Масив згенерований простим range: [0, 1, 2, 3, 4] та методом arange: [0 1 2 3 4]

!!!HOMEWORK!!!
Весь діапазон масиву, згенерований простим range: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Весь діапазон масиву, згенерований методом arange з кроком 3:
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74
 77 80 83 86 89 92 95 98]
Весь діапазон масиву, згенерований методом arange в зворотньому порядку:
 [99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 

In [67]:
a = np.arange(start, size_of_vec)
print(f"Вивід першого елементу масиву: {a[0]}")
print('\n!!!HOMEWORK!!!')
print(f"Вивід останнього елементу масиву: {a[-1]}")

Вивід першого елементу масиву: 5

!!!HOMEWORK!!!
Вивід останнього елементу масиву: 99


In [76]:
x = range(start, size_of_vec)
print("Вивід масиву з вбудованою функцією range:", list(x))
print("Вивід першого значення масиву x[0]=", list(x)[0], )
print('\n!!!HOMEWORK!!!')
print("Вивід значення масиву із середини діапазону x[0]=", list(x)[48], )
#homework("Виведіть якесь число з середини діапазону.")

Вивід масиву з вбудованою функцією range: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Вивід першого значення масиву x[0]= 5

!!!HOMEWORK!!!
Вивід значення масиву із середини діапазону x[0]= 53


In [96]:
x = np.arange(10.4)
print("Виводимо масив х:", x)
x = np.arange(0.5, 4, 0.5)
print("Виводимо масив х на проміжку від [0.5; 4] з кроком 0.5:", x)
x = np.arange(0.04, 1.84, 0.08)
print("Виводимо масив х на проміжку від [0.04; 1.84] з кроком 0.08:\n", x)
print("\n!!!Там, де можливо, Python автоматично заокруглює значення (відкидає зайві нулі)!!!")
print('\n!!!HOMEWORK!!!')
x = np.arange(0.1, 0.101, 0.0001)
print("Виводимо масив х на проміжку від [0.04; 1.84] з кроком 0.08:\n", x)
y = x * 2.5
print("Результат множення елементів масиву  на 2.5:", y)
z = y**2/0.4
print("Результат піднесення елементів масиву до квадрату та ділення на 0.4:", z)

Виводимо масив х: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Виводимо масив х на проміжку від [0.5; 4] з кроком 0.5: [0.5 1.  1.5 2.  2.5 3.  3.5]
Виводимо масив х на проміжку від [0.04; 1.84] з кроком 0.08:
 [0.04 0.12 0.2  0.28 0.36 0.44 0.52 0.6  0.68 0.76 0.84 0.92 1.   1.08
 1.16 1.24 1.32 1.4  1.48 1.56 1.64 1.72 1.8 ]

!!!Там, де можливо, Python автоматично заокруглює значення (відкидає нулі)!!!

!!!HOMEWORK!!!
Виводимо масив х на проміжку від [0.04; 1.84] з кроком 0.08:
 [0.1    0.1001 0.1002 0.1003 0.1004 0.1005 0.1006 0.1007 0.1008 0.1009
 0.101 ]
Результат множення елементів масиву  на 2.5: [0.25    0.25025 0.2505  0.25075 0.251   0.25125 0.2515  0.25175 0.252
 0.25225 0.2525 ]
Результат піднесення елементів масиву до квадрату та ділення на 0.4: [0.15625    0.15656266 0.15687563 0.15718891 0.1575025  0.15781641
 0.15813063 0.15844516 0.15876    0.15907516 0.15939063]


### Метод linspace - генерує задану кількістю чисел у певному діапазоні, 50 чисел за замовчуванням

In [115]:
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні від {a[0]} до {a[-1]}")
print(f"Власне числа: {a}")

Згенерували 50 чисел в діапазоні від 5.0 до 100.0
Власне числа: [  5.           6.93877551   8.87755102  10.81632653  12.75510204
  14.69387755  16.63265306  18.57142857  20.51020408  22.44897959
  24.3877551   26.32653061  28.26530612  30.20408163  32.14285714
  34.08163265  36.02040816  37.95918367  39.89795918  41.83673469
  43.7755102   45.71428571  47.65306122  49.59183673  51.53061224
  53.46938776  55.40816327  57.34693878  59.28571429  61.2244898
  63.16326531  65.10204082  67.04081633  68.97959184  70.91836735
  72.85714286  74.79591837  76.73469388  78.67346939  80.6122449
  82.55102041  84.48979592  86.42857143  88.36734694  90.30612245
  92.24489796  94.18367347  96.12244898  98.06122449 100.        ]


In [123]:
print("!!!HOMEWORK!!! Виведемо кожне друге число згенерованого діапазону. Для цього використаємо цикл for :)")
for i in range(0,len(a),2):
    print(a[i])

!!!HOMEWORK!!! Виведемо кожне друге число згенерованого діапазону. Для цього використаємо цикл for :)
5.0
8.877551020408163
12.755102040816325
16.632653061224488
20.51020408163265
24.387755102040817
28.26530612244898
32.14285714285714
36.0204081632653
39.89795918367347
43.775510204081634
47.6530612244898
51.53061224489796
55.40816326530612
59.285714285714285
63.16326530612245
67.0408163265306
70.91836734693878
74.79591836734694
78.6734693877551
82.55102040816327
86.42857142857143
90.3061224489796
94.18367346938776
98.06122448979592


In [161]:
print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
print('\n!!!HOMEWORK!!!')
print("Збільшимо кількість чисел до 100. Виведемо перших та останніх 10.")
k = np.linspace(start, size_of_vec, 100)
print('\nПерших 10 чисел:', k[0:10])
print('\nОстанніх 10 чисел:', k[-11:-1])

Можна зменшити кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]

!!!HOMEWORK!!!
Збільшимо кількість чисел до 100. Виведемо перших та останніх 10.

Перших 10 чисел: [ 5.          5.95959596  6.91919192  7.87878788  8.83838384  9.7979798
 10.75757576 11.71717172 12.67676768 13.63636364]

Останніх 10 чисел: [90.4040404  91.36363636 92.32323232 93.28282828 94.24242424 95.2020202
 96.16161616 97.12121212 98.08080808 99.04040404]


In [159]:
print("""\nЯк бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.""")
print(np.linspace(start, size_of_vec, 5, endpoint=False))
print('\n!!!HOMEWORK!!!')
step=(size_of_vec-start)/4
print('Порахуємо крок вручну (останнє значення включене у згенерований діапазон) step=', step)

print(f"\nДля порівняння, визначимо крок автоматично, коли:")
_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print('-останнє значення включене у згенерований діапазон step1=', sp_1)
print('-останнє значення виключене із згенерованого діапазону step2=', sp_2)
print("""Як бачимо кроки step1 і step2 відрізняються, оскільки, при обчисленні step1 останнє значення включене у згенерований діапазон, 
а при обчисленні step2 останнє значення виключене із згенерованого діапазону.""")


Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
[ 5. 24. 43. 62. 81.]

!!!HOMEWORK!!!
Порахуємо крок вручну (останнє значення включене у згенерований діапазон) step= 23.75

Для порівняння, визначимо крок автоматично, коли:
-останнє значення включене у згенерований діапазон step1= 23.75
-останнє значення виключене із згенерованого діапазону step2= 19.0
Як бачимо кроки step1 і step2 відрізняються, оскільки, при обчисленні step1 останнє значення включене у згенерований діапазон, 
а при обчисленні step2 останнє значення виключене із згенерованого діапазону.


### Типи масивів/векторів, багатовимірні масиви, розуміння вимірів

In [16]:
print('\n!!!HOMEWORK!!!\n')
print("""ndim - кількість вимірів масиву NumPy як ціле число int;
shape - форма (= довжина кожного виміру) масиву NumPy як кортеж;
\tНавіть у випадку одновимірного масиву це кортеж з одним елементом замість цілого значення.
\t!!! Кортеж з одним елементом має кінцеву кому (3,)!!!
\tНаприклад, у випадку двовимірного масиву shape - це (number of rows - кількість рядків, number of columns - кількість стовпців).
\tЯкщо треба отримати лише кількість рядків або стовпців, то можна отримати кожен елемент кортежу.
size - це розмір (= загальна кількість елементів) масиву NumPy""")

import numpy as np
examples = {
    'Скаляр': np.array(7), 
    'Вектор Рядок': np.array([7, 7, 7, 7, 7]), 
    'Вектор Стовпець': np.array([[7], [7], [7]]), 
    'Матриця': np.array([[7, 7],[7, 7], [7, 7], [7, 7], [7, 7]]),
    'Багатовимірна Матриця': np.array([ [[7, 7], [7, 7], [7, 7], [7, 7]],
                                        [[7, 7], [7, 7], [7, 7], [7, 7]],
                                        [[7, 7], [7, 7], [7, 7], [7, 7]],
                                        [[7, 7], [7, 7], [7, 7], [7, 7]] ])
    }
for key in examples:
    print(f"\nРозглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-"*10)


!!!HOMEWORK!!!

ndim - кількість вимірів масиву NumPy як ціле число int;
shape - форма (= довжина кожного виміру) масиву NumPy як кортеж;
	Навіть у випадку одновимірного масиву це кортеж з одним елементом замість цілого значення.
	!!! Кортеж з одним елементом має кінцеву кому (3,)!!!
	Наприклад, у випадку двовимірного масиву shape - це (number of rows - кількість рядків, number of columns - кількість стовпців).
	Якщо треба отримати лише кількість рядків або стовпців, то можна отримати кожен елемент кортежу.
size - це розмір (= загальна кількість елементів) масиву NumPy

Розглядаємо приклад з Скаляр. 
Значення x буде: 
 7
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів х: 1
-=--=--=--=--=--=--=--=--=--=-

Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [7 7 7 7 7]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (5,)
Кількість елементів х: 5
-=--=--=--=--=--=--=--

In [19]:
print('\n!!!HOMEWORK!!!\n')
examples = {
    '3 рядків': np.array([[3], [3], [3]]), 
    '4 стовпців': np.array([[4, 4, 4, 4]]),
    '7 елементів': np.array([[[7, 7, 7, 7, 7, 7, 7]]])
    }
for a in examples:
    print(f"Для {a} маємо shape: \n{examples[a].shape} \nта вигляд: \n{examples[a]}")


!!!HOMEWORK!!!

Для 3 рядків маємо shape: 
(3, 1) 
та вигляд: 
[[3]
 [3]
 [3]]
Для 4 стовпців маємо shape: 
(1, 4) 
та вигляд: 
[[4 4 4 4]]
Для 7 елементів маємо shape: 
(1, 1, 7) 
та вигляд: 
[[[7 7 7 7 7 7 7]]]


### Indexing and Slicing

In [24]:
print('\n!!!HOMEWORK!!!\n')
F = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99, 1010])
print(f"""Масив: {F}
Виміри: {F.shape}
Нумерація масивів відбувається з 0.
Отже, перший елемент масиву: {F[0]}
Другий елемент масиву: {F[1]}
Останній елемент масиву: {len(F)}: \n {F[9]}""")

print(f"""Для доступу з кінця масиву скористаємось від`ємними індексами.
Останній елемент масиву: {F[-1]}
Передостанній елемент масиву: {F[-2]}
Весь масив задом наперед: {F[::-1]}""")


!!!HOMEWORK!!!

Масив: [  11   22   33   44   55   66   77   88   99 1010]
Виміри: (10,)
Нумерація масивів відбувається з 0.
Отже, перший елемент масиву: 11
Другий елемент масиву: 22
Останній елемент масиву: 10: 
 1010
Для доступу з кінця масиву скористаємось від`ємними індексами.
Останній елемент масиву: 1010
Передостанній елемент масиву: 99
Весь масив задом наперед: [1010   99   88   77   66   55   44   33   22   11]


In [28]:
print('\n!!!HOMEWORK!!!\n')
A = np.array([ [0.1, 0.2, 0.3, 0.4], 
               [1.1, 1.2, 1.3, 1.4],
               [2.1, 2.2, 2.3, 2.4],
               [3.1, 3.2, 3.3, 3.4]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Щоб вивести цілий рядок, досить задати одне значення:
    Виведемо весь перший рядок: {A[0]}
    Виведемо весь останній рядок: {A[-1]}
Щоб взяти цілий стовпець (символ ':' вказує взяти всі елементи): 
    Виведемо весь перший стовпець: {A[:,0]}
    Виведемо весь останній стовпець: {A[:,-1]}
Щоб отримати конкретний елемент, треба задати два значення: 
    Виведемо перший елемент: {A[0][0]} або {A[0, 0]}
    Виведемо останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")
print(f"""Виведемо елементи, які належать діагоналі: 
{A[0][0]}\t{A[1][1]}\t{A[2][2]}\t{A[3][3]}""")
#homework("Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі.")


!!!HOMEWORK!!!

Масив:
[[0.1 0.2 0.3 0.4]
 [1.1 1.2 1.3 1.4]
 [2.1 2.2 2.3 2.4]
 [3.1 3.2 3.3 3.4]]
Виміри: (4, 4)
Щоб вивести цілий рядок, досить задати одне значення:
    Виведемо весь перший рядок: [0.1 0.2 0.3 0.4]
    Виведемо весь останній рядок: [3.1 3.2 3.3 3.4]
Щоб взяти цілий стовпець (символ ':' вказує взяти всі елементи): 
    Виведемо весь перший стовпець: [0.1 1.1 2.1 3.1]
    Виведемо весь останній стовпець: [0.4 1.4 2.4 3.4]
Щоб отримати конкретний елемент, треба задати два значення: 
    Виведемо перший елемент: 0.1 або 0.1
    Виведемо останній елемент: 3.3 або 3.4 або 3.4

Виведемо елементи, які належать діагоналі: 
0.1	1.2	2.3	3.4


In [47]:
S = np.array([5, 6, 7, 8, 9, 3, 1, 2, 4, 0])

print(f"""Масив:
{S}
Виміри: {S.shape}
Вивід елементів від другого і до восьмого (не включаючи восьмий): {S[2:8]}
Вивід перших 7 елементів: {S[:7]}
Вивід елементів від заданого до кінця: {S[4:]}
Вивід всіх елементів: {S[:]}
""")
print(f"""Виведемо чотири значення з кінця масиву: {S[6:]}
Виведемо п'ять значень з кінця масиву у зворотньому напрямку: {S[:-6:-1]}""")

Масив:
[5 6 7 8 9 3 1 2 4 0]
Виміри: (10,)
Вивід елементів від другого і до восьмого (не включаючи восьмий): [7 8 9 3 1 2]
Вивід перших 7 елементів: [5 6 7 8 9 3 1]
Вивід елементів від заданого до кінця: [9 3 1 2 4 0]
Вивід всіх елементів: [5 6 7 8 9 3 1 2 4 0]

Виведемо чотири значення з кінця масиву: [1 2 4 0]
Виведемо п'ять значень з кінця масиву у зворотньому напрямку: [0 4 2 1 3]


In [81]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

print(f"""Матриця А:
{A}
Виміри: {A.shape}
Виводимо перших два рядки: 
{A[0:2]}
Виводимо перших два стовпці: 
{A[:, 0:2]}
Виводимо два останніх рядка:
{A[3:, :]}
Виводимо підматрицю (нижні елементи): 
{A[-3:, -3:]}
""")

Матриця А:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Виміри: (5, 5)
Виводимо перших два рядки: 
[[11 12 13 14 15]
 [21 22 23 24 25]]
Виводимо перших два стовпці: 
[[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]
Виводимо два останніх рядка:
[[41 42 43 44 45]
 [51 52 53 54 55]]
Виводимо підматрицю (нижні елементи): 
[[33 34 35]
 [43 44 45]
 [53 54 55]]



In [80]:
print('\n!!!HOMEWORK!!!\n')
print(f"""Виведемо матрицю розмірністю 2х2 з нижнього лівого кута:
{A[3:5, 0:2]}
Виведемо матрицю розмірністю 2х2 з нижнього правого кута:
{A[3:5, 3:5]}
Виведемо матрицю розмірністю 2х2 з верхнього лівого кута:
{A[0:2, 0:2]}
Виведемо матрицю розмірністю 2х2 з верхнього правого кута:
{A[0:2, 3:5]}""")


!!!HOMEWORK!!!

Виведемо матрицю розмірністю 2х2 з нижнього лівого кута:
[[41 42]
 [51 52]]
Виведемо матрицю розмірністю 2х2 з нижнього правого кута:
[[44 45]
 [54 55]]
Виведемо матрицю розмірністю 2х2 з верхнього лівого кута:
[[11 12]
 [21 22]]
Виведемо матрицю розмірністю 2х2 з верхнього правого кута:
[[14 15]
 [24 25]]


In [93]:
A = np.arange(28).reshape(4, 7)
print('\n!!!HOMEWORK!!!\n')
print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен другий елемент другого рядка: 
{A[1, ::2]}
Беремо кожен третій елемент останнього рядка: 
{A[3, ::3]}
Кожен другий елемент в кожному другому рядку: 
{A[::2, ::2]}
Останні два елементи в кожному другому рядку:
{A[::2, 5:]}
Можна повнісню змінити порядок елементів (дзерально обернемо):
{A[::-1, ::-1]}
""")


!!!HOMEWORK!!!

Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)
Беремо кожен другий елемент другого рядка: 
[ 7  9 11 13]
Беремо кожен третій елемент останнього рядка: 
[21 24 27]
Кожен другий елемент в кожному другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]
Останні два елементи в кожному другому рядку:
[[ 5  6]
 [19 20]]
Можна повнісню змінити порядок елементів (дзерально обернемо):
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]



In [98]:
A = np.arange(50)
all_even = (A%2!=0) # парні
complex = (A<30) & (A/5<2) 

print('\n!!!HOMEWORK!!!\n')
print("Виведемо всі непарні числа з даного масиву:\n")
print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.

Після підставляння умови пошуку непарних чисел в масив отримаємо:
{A[all_even]}""")


!!!HOMEWORK!!!

Виведемо всі непарні числа з даного масиву:

Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або False для 0 або True для 1.

Після підставляння умови пошуку непарних чисел в масив отримаємо:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


### Функції для створення матриць: ones, zeros, identity, eye, empty

In [101]:
o = np.ones(5)
z = np.zeros(5)
i = np.identity(5)
e = np.eye(5)
t = np.empty(5)

print(f"""
Всі елементи 1: {o}
Всі елементи 0: {z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел, які записані у пам`ять, де був ініціалізований масив:
{t}
""")


Всі елементи 1: [1. 1. 1. 1. 1.]
Всі елементи 0: [0. 0. 0. 0. 0.]
Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця буде містити набір випадкових чисел, які записані у пам`ять, де був ініціалізований масив:
[0. 0. 0. 0. 0.]

